language: python

python:
        - "3.6.12"

before_install:
        - sudo python -m pip install pipenv

install:
        - pipenv install --dev

script:
        - pipenv run nosetests tests/

notifications:
        email: false

