language: python

python:
        - "3.9.10"

before_install:
        - python -m venv --upgrade-deps .venv

install:
        - source .venv/bin/activate
        - pip install -r requirements/dev .

script:
        - nosetests tests/

notifications:
        email: false

